-- Dados de demonstração (idempotente). Espelha sautek/data.jsx.

INSERT INTO companies (id, name, segment, tagline, city, uf, rating, reviews, verified, founded, employees, services, badges, about, phone, site, email, atende_ufs) VALUES
('medlab','MedLab Diagnósticos','lab','Análises clínicas e apoio laboratorial para redes de saúde','Campinas','SP',4.8,312,TRUE,2004,'500–1.000',
  ARRAY['Apoio laboratorial 24h','Coleta domiciliar','Análises moleculares','Anatomia patológica','Telemedicina diagnóstica'],
  ARRAY['ISO 9001','PALC / SBPC','ANVISA'],
  'Rede de apoio laboratorial com mais de 4.000 exames no catálogo e logística refrigerada própria, atendendo hospitais e clínicas em todo o estado.',
  '(19) 3000-1200','medlab.com.br','contato@medlab.com.br',ARRAY['SP','RJ','MG','PR']),
('tecvida','TecVida Equipamentos','equip','Equipamentos hospitalares e monitorização multiparâmetros','São Paulo','SP',4.6,198,TRUE,1998,'200–500',
  ARRAY['Monitores de sinais vitais','Ventiladores pulmonares','Bombas de infusão','Comodato de equipamentos','Treinamento técnico'],
  ARRAY['ANVISA','ISO 13485','Inmetro'],
  'Importação e distribuição de equipamentos médico-hospitalares com assistência técnica certificada e contratos de comodato para UTIs.',
  '(11) 4002-8922','tecvida.com.br',NULL,'{}'),
('higitec','Higitec Serviços Hospitalares','limpeza','Limpeza terminal e controle de infecção hospitalar','Rio de Janeiro','RJ',4.5,144,TRUE,2009,'1.000+',
  ARRAY['Limpeza concorrente e terminal','Higienização de áreas críticas','Gestão de enxoval','Controle de pragas','Equipe dedicada 24/7'],
  ARRAY['ISO 9001','NR-32','RDC 222'],
  'Especializada em higiene hospitalar com protocolos alinhados à CCIH e equipes residentes treinadas para áreas críticas.',
  '(21) 3500-7700','higitec.com.br',NULL,'{}'),
('bioresiduos','BioResíduos Ambiental','residuos','Coleta e tratamento de resíduos de serviços de saúde','Curitiba','PR',4.7,89,TRUE,2011,'200–500',
  ARRAY['Coleta de resíduos grupo A/B/E','Tratamento por autoclave','Logística reversa','Manifesto digital (MTR)','Relatórios de conformidade'],
  ARRAY['IBAMA','RDC 222','PGRSS'],
  'Gestão completa de resíduos de saúde com rastreabilidade digital ponta a ponta e licenças ambientais para todo o Sul do país.',
  '(41) 3200-5050','bioresiduos.com.br',NULL,'{}'),
('sterilpro','SterilPro Centro de Materiais','esteril','Esterilização terceirizada e processamento de materiais','Belo Horizonte','MG',4.9,76,TRUE,2015,'50–200',
  ARRAY['Esterilização por óxido de etileno','Autoclave a vapor','Rastreabilidade por lote','Reprocessamento OPME','Validação de processos'],
  ARRAY['ANVISA','ISO 11135','RDC 15'],
  'Central de processamento de materiais (CME) terceirizada com rastreabilidade individual de instrumentais e indicadores biológicos.',
  '(31) 3400-9090','sterilpro.com.br',NULL,'{}'),
('clinsys','ClinSys Software','ti','Prontuário eletrônico e gestão para clínicas e hospitais','Florianópolis','SC',4.4,421,TRUE,2013,'200–500',
  ARRAY['Prontuário eletrônico (PEP)','Faturamento TISS','Agenda e telemedicina','BI assistencial','Integração com laboratórios'],
  ARRAY['LGPD','Certif. SBIS-CFM','ISO 27001'],
  'Plataforma de gestão em saúde com prontuário eletrônico certificado, faturamento de convênios e painéis de indicadores assistenciais.',
  '(48) 3030-1010','clinsys.com.br',NULL,'{}'),
('telesaude','TeleSaúde Connect','tele','Plataforma de teleconsulta e laudos à distância','São Paulo','SP',4.3,167,FALSE,2019,'50–200',
  ARRAY['Teleconsulta white-label','Laudos de imagem remotos','Segunda opinião médica','Triagem digital','API de integração'],
  ARRAY['LGPD','CFM 2.314/22'],
  'Infraestrutura de telemedicina para operadoras e hospitais, com fila inteligente de atendimento e emissão de laudos por especialistas.',
  '(11) 4003-3344','telesaude.io',NULL,'{}'),
('oxivida','OxiVida Gases Medicinais','gases','Oxigênio medicinal e redes de gases hospitalares','Porto Alegre','RS',4.6,58,TRUE,2001,'200–500',
  ARRAY['Oxigênio medicinal','Ar comprimido medicinal','Projeto e manutenção de redes','Cilindros e tanques criogênicos','Plantão de emergência'],
  ARRAY['ANVISA','RDC 870','ABNT NBR'],
  'Fornecimento de gases medicinais e instalação de redes hospitalares com telemetria de nível e atendimento emergencial 24h.',
  '(51) 3100-6060','oxivida.com.br',NULL,'{}'),
('manutmed','ManutMed Engenharia Clínica','manut','Engenharia clínica e manutenção preventiva certificada','Ribeirão Preto','SP',4.7,103,TRUE,2008,'50–200',
  ARRAY['Manutenção preventiva e corretiva','Calibração e segurança elétrica','Gestão de parque tecnológico','Laudos para acreditação','Plantão técnico'],
  ARRAY['RDC 02/2010','Inmetro','ISO 9001'],
  'Engenharia clínica completa para gestão do parque de equipamentos, com indicadores de disponibilidade e suporte a processos de acreditação.',
  '(16) 3600-2020','manutmed.com.br',NULL,'{}'),
('vestmed','VestMed Uniformes & EPI','epi','Vestuário hospitalar e equipamentos de proteção','Blumenau','SC',4.2,64,FALSE,2006,'50–200',
  ARRAY['Aventais e jalecos','Campos cirúrgicos','EPI descartável','Personalização e bordado','Logística por assinatura'],
  ARRAY['CA / MTE','ABNT NBR 16064'],
  'Confecção e distribuição de vestuário hospitalar e EPIs com certificado de aprovação e programa de reposição automática.',
  '(47) 3300-4040','vestmed.com.br',NULL,'{}'),
('nutricare','NutriCare Hospitalar','nutri','Nutrição clínica e terapia nutricional para internados','Salvador','BA',4.5,71,TRUE,2012,'200–500',
  ARRAY['Terapia nutricional enteral/parenteral','Cozinha hospitalar terceirizada','Dietas especiais','Consultoria de EMTN','Controle de custos'],
  ARRAY['ANVISA','RDC 63','ISO 22000'],
  'Operação de nutrição hospitalar e terapia nutricional com equipe multiprofissional e protocolos de segurança alimentar.',
  '(71) 3200-8080','nutricare.com.br',NULL,'{}'),
('farmadistribui','FarmaDistribui Logística','farma','Distribuição farmacêutica com cadeia de frio validada','São Paulo','SP',4.4,235,TRUE,1996,'1.000+',
  ARRAY['Medicamentos e materiais','Cadeia de frio validada','Reposição por consignação','Gestão de farmácia hospitalar','Entrega expressa'],
  ARRAY['ANVISA','RDC 304','Boas Práticas'],
  'Distribuidora farmacêutica com central refrigerada validada, atendimento a hospitais e clínicas e reposição automática por nível de estoque.',
  '(11) 4005-6000','farmadistribui.com.br',NULL,'{}')
ON CONFLICT (id) DO NOTHING;

INSERT INTO solicitacoes (id, solicitante, cargo, organizacao, tipo, status, prestador, prestador_id, uf, cidade, email, phone, quando, resumo) VALUES
('SOL-2041','Mariana Alves','Coordenadora de Suprimentos','Hospital Santa Lúcia','cotacao','nova','MedLab Diagnósticos','medlab','SP','Campinas','compras@santalucia.com.br','(19) 3232-1010','há 2 horas','Apoio laboratorial 24h para nova unidade — 12 mil exames/mês.'),
('SOL-2040','Dr. Paulo Renato','Diretor Técnico','Clínica Vida Plena','contato','nova','MedLab Diagnósticos','medlab','RJ','Niterói','diretoria@vidaplena.com.br','(21) 2710-4422','há 5 horas','Gostaria de conversar sobre coleta domiciliar para pacientes crônicos.'),
('SOL-2038','Fernanda Costa','Gerente de Compras','Rede SaúdeMais','cotacao','andamento','MedLab Diagnósticos','medlab','MG','Belo Horizonte','fernanda@saudemais.com.br','(31) 3045-7788','ontem','Cotação de análises moleculares para 3 hospitais da rede.'),
('SOL-2035','Ricardo Tavares','Suprimentos','Instituto Oncológico SP','parceria','andamento','MedLab Diagnósticos','medlab','SP','São Paulo','ricardo@iosp.org.br','(11) 3567-9000','há 2 dias','Proposta de parceria para anatomia patológica com SLA dedicado.'),
('SOL-2031','Juliana Prado','Enfermeira-chefe','Maternidade Aurora','cotacao','respondida','MedLab Diagnósticos','medlab','PR','Curitiba','juliana@aurora.com.br','(41) 3220-5566','há 3 dias','Exames de triagem neonatal — volume estimado 400/mês.'),
('SOL-2028','Marcos Vinícius','Compras','Hospital Regional Norte','contato','respondida','MedLab Diagnósticos','medlab','BA','Salvador','marcos@hrn.ba.gov.br','(71) 3611-2200','há 4 dias','Informações sobre apoio laboratorial em regime de plantão.'),
('SOL-2022','Camila Restani','Administradora','Clínica Imagem Sul','cotacao','fechada','MedLab Diagnósticos','medlab','RS','Porto Alegre','camila@imagemsul.com.br','(51) 3019-4433','há 1 semana','Pacote de exames laboratoriais de rotina — fechado contrato anual.'),
('SOL-2019','André Lopes','Coordenador','UPA Central','cotacao','fechada','MedLab Diagnósticos','medlab','SC','Joinville','andre@upacentral.sc.gov.br','(47) 3433-1100','há 2 semanas','Exames de urgência com laudo em até 60 min.')
ON CONFLICT (id) DO NOTHING;
